# Generated by Django 5.2.1 on 2025-06-18 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject_template', models.CharField(help_text='صيغة عنوان الإيميل مع متغيرات مثل {{ appointment.date }}', max_length=200)),
                ('html_template_path', models.CharField(help_text="مسار ملف القالب داخل templates، مثلاً 'emails/appointment_confirmation.html'", max_length=200)),
                ('text_template_path', models.CharField(blank=True, help_text='مسار قالب نصي بسيط (اختياري)', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('context', models.JSONField(help_text="بيانات لتمريرها للقالب، مثلاً {'appointment': appointment, 'user': user}")),
                ('status', models.IntegerField(choices=[(1, 'pending'), (2, 'sent'), (3, 'failed')], default=1)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
