# Generated by Django 5.2.1 on 2025-06-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=5000, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(max_length=4)),
                ('appointment_status', models.IntegerField(choices=[(0, 'done'), (1, 'pending'), (2, 'canceled')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=5000, null=True)),
                ('address', models.CharField(max_length=255)),
                ('added_at', models.DateField(blank=True, help_text='department opening date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('job', models.IntegerField(choices=[(1, 'secretary'), (2, 'nurse'), (3, 'technician'), (4, 'doctor'), (5, 'worker'), (6, 'other'), (7, 'admin')], default=6)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
