# Generated by Django 5.2.1 on 2025-06-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsAndSurgeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('duration_minutes', models.IntegerField()),
                ('dental_type', models.IntegerField(choices=[(1, 'Dental Cleaning (Prophylaxis)'), (2, 'Dental Filling (Restoration)'), (3, 'Root Canal Therapy (Endodontics)'), (4, 'Tooth Extraction'), (5, 'Dental Implant Placement'), (6, 'Teeth Whitening'), (7, 'Orthodontic Treatment'), (8, 'Periodical Checking')], default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=1600)),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider')),
                ('order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='appointment',
            name='dental_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Dental Cleaning (Prophylaxis)'), (2, 'Dental Filling (Restoration)'), (3, 'Root Canal Therapy (Endodontics)'), (4, 'Tooth Extraction'), (5, 'Dental Implant Placement'), (6, 'Teeth Whitening'), (7, 'Orthodontic Treatment'), (8, 'Periodical Checking')], null=True),
        ),
    ]
