# Generated by Django 5.2.1 on 2025-06-19 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_operationsandsurgeries_slider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='dental_type',
        ),
        migrations.AddField(
            model_name='appointment',
            name='operations_and_surgeries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='clinic.operationsandsurgeries'),
        ),
        migrations.AddField(
            model_name='operationsandsurgeries',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='operations_and_surgeries/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slider/'),
        ),
    ]
