# Generated by Django 5.2.1 on 2025-06-27 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='operations_and_surgeries',
            new_name='operation',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='department',
            name='contact',
            field=models.CharField(blank=True, help_text='phone number , fax, etc...', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.RenameModel(
            old_name='OperationsAndSurgeries',
            new_name='Operation',
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role', to='clinic.operation')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role', to='clinic.worker')),
            ],
            options={
                'unique_together': {('worker', 'operation')},
            },
        ),
    ]
